'use strict';
var assert=require('assert'),crypto=require('crypto'),fixture=require('./phone-fixture'),hash=require('../src/pkjs/checksums'),manifest=require('../src/pkjs/manifest'),binary=require('../src/pkjs/binary'),settings=require('../src/pkjs/settings'),nearby=require('../src/pkjs/nearby'),createTransfer=require('../src/pkjs/transfer'),createUpdater=require('../src/pkjs/updater');
var config={manifestUrl:'https://feed.example/manifest.json',coverage:'minami-kasugaoka-v1',appVersion:1,maxPayload:32768,manifestMaxBytes:8192,requestTimeout:15000},now=Date.parse('2026-10-01T00:00:00Z');
function clone(v){return JSON.parse(JSON.stringify(v));}
function clock(){var time=now,timers=[],id=0;return{now:function(){return time;},schedule:function(fn,delay){timers.push({id:++id,at:time+delay,fn:fn});return id;},cancel:function(n){timers=timers.filter(function(t){return t.id!==n;});},advance:function(ms){var target=time+ms;while(true){timers.sort(function(a,b){return a.at-b.at;});if(!timers.length||timers[0].at>target)break;var timer=timers.shift();time=timer.at;timer.fn();}time=target;}};}
var count=0;function test(name,fn){fn();count+=1;console.log('PASS '+name);}
test('protocol preserves unsigned words through signed PebbleKit tuples',function(){var p=require('../src/pkjs/protocol'),message={TYPE:5,SESSION:4294967295,CRC:0xcbf43926,STAMP:2147483648,DATA:[255,128,0]},wire=p.wire(message);assert.strictEqual(wire.SESSION,-1);assert.strictEqual(wire.CRC,-873187034);assert.strictEqual(wire.STAMP,-2147483648);assert.strictEqual(p.get(wire,'SESSION'),4294967295);assert.strictEqual(p.get({'5':wire.CRC},'CRC'),0xcbf43926);assert.strictEqual(p.get(wire,'STAMP'),2147483648);assert.strictEqual(wire.DATA,message.DATA);assert.strictEqual(message.SESSION,4294967295);});
test('shared sender waits for transport callback after an early application ACK',function(){var c=clock(),wire=[],sender=require('../src/pkjs/sender')(Object.assign(c,{send:function(message,ok,fail){wire.push({message:message,ok:ok,fail:fail});}})),t=createTransfer(Object.assign({},c,{send:sender}));t.start([1,2],{version:2,crc32:0xcbf43926},function(){},0);assert.strictEqual(wire.length,1);assert.strictEqual(wire[0].message.CRC,-873187034);t.receive({TYPE:8,SESSION:wire[0].message.SESSION,SEQ:0,STATUS:0,FLAGS:5});assert.strictEqual(wire.length,1,'CHUNK must wait for BEGIN transport callback');assert.strictEqual(sender.pending(),2);wire[0].ok();assert.strictEqual(wire.length,2);assert.strictEqual(wire[1].message.TYPE,6);t.receive({TYPE:8,SESSION:wire[1].message.SESSION,SEQ:0,STATUS:0,FLAGS:6});assert.strictEqual(wire.length,2,'COMMIT must wait for CHUNK transport callback');wire[1].ok();assert.strictEqual(wire[2].message.TYPE,7);t.receive({TYPE:8,SESSION:wire[2].message.SESSION,SEQ:65535,STATUS:3,FLAGS:7});wire[2].ok();assert.strictEqual(sender.pending(),0);});
test('shared sender bounds FIFO and handles NACK without concurrent transactions',function(){var c=clock(),wire=[],results=[],sender=require('../src/pkjs/sender')(Object.assign(c,{maxQueue:2,send:function(message,ok,fail){wire.push({message:message,ok:ok,fail:fail});}}));sender({TYPE:1},function(){results.push('first');});sender({TYPE:2},null,function(error){results.push(error.message);});assert.strictEqual(sender({TYPE:3},null,function(error){results.push(error.message);}),false);assert.strictEqual(wire.length,1);assert.strictEqual(sender.pending(),2);wire[0].ok();assert.strictEqual(wire.length,2);assert.strictEqual(wire[1].message.TYPE,2);wire[1].fail(new Error('Native NACK'));assert.deepStrictEqual(results,['Transport queue is full','first','Native NACK']);assert.strictEqual(sender.pending(),0);});
test('shared sender timeout blocks new transactions until callback or reconnect',function(){var c=clock(),wire=[],errors=[],sender=require('../src/pkjs/sender')(Object.assign(c,{send:function(message,ok,fail){wire.push({message:message,ok:ok,fail:fail});}}));sender({TYPE:1},null,function(e){errors.push(e.message);});sender({TYPE:2},null,function(e){errors.push(e.message);});c.advance(10000);assert.deepStrictEqual(errors,['Transport acknowledgement timeout','Transport unavailable']);assert.strictEqual(sender({TYPE:3},null,function(e){errors.push(e.message);}),false);assert.strictEqual(wire.length,1);wire[0].ok();sender({TYPE:4});assert.strictEqual(wire.length,2);sender.reset();sender({TYPE:5});assert.strictEqual(wire.length,3);wire[1].ok();assert.strictEqual(sender.pending(),1,'old callback cannot complete a new transaction');wire[2].ok();assert.strictEqual(sender.pending(),0);});
test('shared sender reports immediate SDK exceptions once',function(){var c=clock(),errors=[],sender=require('../src/pkjs/sender')(Object.assign(c,{send:function(){throw new Error('SDK unavailable');}}));sender({TYPE:1},null,function(error){errors.push(error.message);});assert.deepStrictEqual(errors,['SDK unavailable']);assert.strictEqual(sender.pending(),0);c.advance(10000);assert.strictEqual(errors.length,1);});
test('standard CRC32 and SHA256 vectors',function(){[[],[97,98,99],Array.from({length:32768},function(_,n){return n&255;})].forEach(function(bytes){assert.strictEqual(hash.sha256(bytes),crypto.createHash('sha256').update(Buffer.from(bytes)).digest('hex'));});assert.strictEqual(hash.crc32(Array.from(Buffer.from('123456789'))),0xcbf43926);});
var bytes=fixture(2),release=fixture.release(bytes,'https://feed.example/releases/2.bin'),feed={schema:1,coverage:config.coverage,published:'2026-10-01',current:release,upcoming:null};
test('valid complete binary and manifest agree',function(){assert.strictEqual(manifest.validate(feed,config,now).current.version,2);var v=binary.validate(bytes,config,release);assert.strictEqual(v.departures.length,3);assert.strictEqual(v.catalog.length,2);});
test('reject malformed dates, versions, hosts, lengths, compatibility and future current',function(){[
  function(f){f.current.coverageThrough='2026-02-30';},function(f){f.current.url='http://feed.example/x.bin';},function(f){f.current.url='https://evil.example/x.bin';},function(f){f.current.url='https://feed.example/a/../x.bin';},function(f){f.current.url='https://feed.example/x.bin?redirect=1';},function(f){f.current.bytes=32769;},function(f){f.current.version=0;},function(f){f.current.minAppVersion=2;},function(f){f.schema=2;},function(f){f.coverage='other';},function(f){f.current.effectiveFrom='2026-11-01';},function(f){f.published='2026-02-30';}
].forEach(function(mutate){var f=clone(feed);mutate(f);assert.throws(function(){manifest.validate(f,config,now);});});assert.throws(function(){manifest.origin('http://127.0.0.1:8080/manifest.json',false);});});
function repair(b){var crc=hash.crc32(b,16);for(var i=0;i<4;i+=1)b[12+i]=crc>>>i*8&255;return b;}
test('binary rejects corrupt payload, references, sort, flags, time and UTF8',function(){[function(b){b[130]=255;},function(b){b[50]=1;},function(b){b[128+28+16+3]=2;},function(b){var o=b[64+7*6]+b[65+7*6]*256;b[o]=255;b[o+1]=255;},function(b){var o=b[64+7*6]+b[65+7*6]*256;b[o+2]=99;},function(b){b[b.length-2]=192;},function(b){b[64]=129;}].forEach(function(mutate){var b=bytes.slice();mutate(b);repair(b);assert.throws(function(){binary.validate(b,config);});});var b=bytes.slice();b[150]^=1;assert.throws(function(){binary.validate(b,config);});assert.throws(function(){binary.validate(bytes,config,Object.assign({},release,{sha256:'0'.repeat(64)}));});});
var catalog=[{id:1,label:'Stop one'},{id:2,label:'Stop two'}],preferences={flags:17,defaultId:1,buffer:2,favourites:[2,1],walks:{1:5,2:0}};
test('fixed80B atomic preference roundtrip, explicit unset versus zero',function(){var b=settings.encode(preferences,catalog);assert.strictEqual(b.length,80);assert.deepStrictEqual(settings.decode(b,catalog),preferences);var v=settings.toClay(preferences,catalog);assert.deepStrictEqual(settings.fromClay(v,catalog),preferences);v.Walk1='';assert.strictEqual(settings.fromClay(v,catalog).walks[1],undefined);assert.strictEqual(settings.fromClay(v,catalog).walks[2],0);});
test('startup Nearby requires startup location while None default remains valid',function(){var s=clone(preferences);s.flags=4;assert.throws(function(){settings.encode(s,catalog);},/requires startup location/);s.flags=6;s.defaultId=0;assert.strictEqual(settings.decode(settings.encode(s,catalog),catalog).defaultId,0);var values=settings.toClay(s,catalog);values.LocationEnabled=false;assert.throws(function(){settings.fromClay(values,catalog);},/requires startup location/);});
test('invalid duplicate/unknown/outofrange/padded preferences reject',function(){[function(s){s.favourites=[1,1];},function(s){s.defaultId=99;},function(s){s.walks[1]=121;},function(s){s.buffer=31;},function(s){s.flags=32;}].forEach(function(m){var s=clone(preferences);m(s);assert.throws(function(){settings.encode(s,catalog);});});var b=settings.encode(preferences,catalog);b[6]=1;assert.throws(function(){settings.decode(b,catalog);});b=settings.encode(preferences,catalog);b[34]=256;assert.throws(function(){settings.decode(b,catalog);});var v=settings.toClay(preferences,catalog);v.Walk99='4';assert.throws(function(){settings.fromClay(v,catalog);});});
function position(age,accuracy,latitude){return{timestamp:now-age,coords:{latitude:latitude||34.81,longitude:135.527,accuracy:accuracy}};}
test('Nearby good, stale, poor, outside, missing and stable uncertainty ties',function(){var points=[{id:2,lat:34.81001,lon:135.527,order:0},{id:1,lat:34.81,lon:135.527,order:1}];var result=nearby.rank(position(120000,100),points,now);assert.strictEqual(result.status,0);assert.strictEqual(result.data[0],2);assert.strictEqual(nearby.rank(position(120001,10),points,now).status,2);assert.strictEqual(nearby.rank(position(0,101),points,now).status,1);assert.strictEqual(nearby.rank(position(0,10,35.5),points,now).status,6);assert.strictEqual(nearby.rank(position(0,10),[],now).status,7);assert.strictEqual(nearby.rank({timestamp:now,coords:{latitude:NaN,longitude:135,accuracy:1}},points,now).status,5);});
test('Nearby stale and poor fixes retain real bounded metadata without ranking rows',function(){var points=[{id:1,lat:34.81,lon:135.527,order:0}],stale=position(120001,12.1),poor=position(0,101.2);[stale,poor].forEach(function(fix){var result=nearby.rank(fix,points,now);assert.strictEqual(result.status,fix===stale?2:1);assert.strictEqual(result.stamp,Math.floor(fix.timestamp/1000));assert.strictEqual(result.accuracy,Math.ceil(fix.coords.accuracy));assert.strictEqual(result.data,undefined);var c=clock(),out=[],n=nearby(Object.assign(c,{send:function(m){out.push(m);},geolocation:{getCurrentPosition:function(ok){ok(fix);}}}));n.request(9,2,[1,0,0,0,0,0,0,0,0,0],true);assert.strictEqual(out[0].STATUS,result.status);assert.strictEqual(out[0].STAMP,result.stamp);assert.strictEqual(out[0].ACCURACY,result.accuracy);assert.strictEqual(out[0].DATA,undefined);c.advance(15000);assert.strictEqual(out.length,1);});[NaN,Infinity,-1,4294967296000].forEach(function(stamp){var fix=position(0,10);fix.timestamp=stamp;var result=nearby.rank(fix,points,now);assert.strictEqual(result.status,5);assert.strictEqual(result.stamp,undefined);assert.strictEqual(result.data,undefined);});var future=position(-5001,10);assert.strictEqual(nearby.rank(future,points,now).status,2);assert.strictEqual(nearby.rank(future,points,now).stamp,undefined);var oversized=position(0,4294967296);assert.strictEqual(nearby.rank(oversized,points,now).status,5);var zero=position(0,10);zero.timestamp=0;assert.strictEqual(nearby.rank(zero,points,now).stamp,0);});
test('Nearby denied, unavailable, timeout, missing/throwing API and NaN fix use explicit error states',function(){var fixtures=[{api:{getCurrentPosition:function(ok,error){error({code:1});}},status:3},{api:{getCurrentPosition:function(ok,error){error({code:2});}},status:5},{api:{getCurrentPosition:function(ok,error){error({code:3});}},status:4},{api:null,status:5},{api:{},status:5},{api:{getCurrentPosition:function(){throw new Error('GPS failure');}},status:5},{api:{getCurrentPosition:function(ok){var fix=position(0,1);fix.timestamp=NaN;ok(fix);}},status:5}];fixtures.forEach(function(fixture){var c=clock(),out=[],n=nearby(Object.assign(c,{send:function(m){out.push(m);},geolocation:fixture.api}));n.request(11,2,[1,0,0,0,0,0,0,0,0,0],true);assert.strictEqual(out.length,1);assert.strictEqual(out[0].STATUS,fixture.status);assert.strictEqual(out[0].STAMP,undefined);assert.strictEqual(out[0].ACCURACY,undefined);assert.strictEqual(out[0].DATA,undefined);c.advance(15000);assert.strictEqual(out.length,1);});});
test('one-shot geolocation timeout and obsolete request suppression',function(){var c=clock(),out=[],callbacks=[],opts=Object.assign(c,{send:function(m){out.push(m);},geolocation:{getCurrentPosition:function(ok,error,opt){callbacks.push({ok:ok,error:error});assert.strictEqual(opt.maximumAge,0);}}});var n=nearby(opts),coords=[1,0,0,0,0,0,0,0,0,0];n.request(1,1,coords,true);n.request(2,1,coords,true);callbacks[0].ok(position(0,1));assert.strictEqual(out.length,0);c.advance(15000);assert.strictEqual(out[0].REQUEST,2);assert.strictEqual(out[0].STATUS,4);callbacks[1].ok(position(0,1));assert.strictEqual(out.length,1);n.request(3,1,coords,false);assert.strictEqual(out[1].STATUS,8);});
test('transfer ignores old session/sequence, acknowledges chunks, retries same bytes',function(){var c=clock(),out=[],complete=[],t=createTransfer(Object.assign(c,{send:function(m){out.push(m);}}));t.start(bytes,release,function(e,status){complete.push({error:e,status:status});},7);var begin=out[0];assert.ok(begin.SESSION>0&&begin.SESSION<=2147483647);assert.strictEqual(begin.REQUEST,7);t.receive({TYPE:8,SESSION:begin.SESSION+1,SEQ:0,STATUS:0,FLAGS:5});assert.strictEqual(out.length,1);c.advance(2000);assert.deepStrictEqual(out[1],begin);t.receive({TYPE:8,SESSION:begin.SESSION,SEQ:0,STATUS:0,FLAGS:5});assert.strictEqual(out[2].TYPE,6);t.receive({TYPE:8,SESSION:begin.SESSION,SEQ:0,STATUS:0,FLAGS:5});assert.strictEqual(out.length,3,'late BEGIN ACK cannot advance first chunk');t.receive({TYPE:8,SESSION:begin.SESSION,SEQ:99,STATUS:0,FLAGS:6});assert.strictEqual(out.length,3);while(t.busy()){var m=out[out.length-1];assert.ok(!m.DATA||m.DATA.length<=192);t.receive({TYPE:8,SESSION:m.SESSION,SEQ:m.TYPE===7?65535:m.SEQ||0,STATUS:m.TYPE===7?4:0,FLAGS:m.TYPE});}assert.strictEqual(complete[0].status,4);});
test('transfer gives up after bounded retries without COMMIT',function(){var c=clock(),out=[],error=null,t=createTransfer(Object.assign(c,{send:function(m){out.push(m);}}));t.start(bytes,release,function(e){error=e;},8);c.advance(8000);assert.ok(error);assert.strictEqual(out.length,4);assert.strictEqual(out.some(function(m){return m.TYPE===7;}),false);});
test('unconfigured feed never makes network attempt or successful stamp',function(){var c=clock(),out=[],calls=0,u=createUpdater(Object.assign(c,{config:Object.assign({},config,{manifestUrl:null}),send:function(m){out.push(m);},fetch:function(){calls+=1;}}));u.state({version:1,pending:0,flags:1});u.check(1,true);assert.strictEqual(calls,0);assert.strictEqual(out[0].STATUS,7);assert.strictEqual(out[0].STAMP,undefined);});
test('watch-owned one-inflight and no downgrade/rewrite',function(){var c=clock(),out=[],calls=[],callbacks=[],u=createUpdater(Object.assign(c,{config:config,send:function(m){out.push(m);},fetch:function(url,max,binary,timeout,cb){calls.push(url);callbacks.push(cb);}}));u.state({version:2,pending:3,flags:1});u.check(7,false);u.check(8,true);assert.strictEqual(calls.length,1);callbacks[0](null,JSON.stringify(feed));assert.strictEqual(out[out.length-1].STATUS,2);assert.ok(out[out.length-1].STAMP);assert.strictEqual(calls.length,1);});
test('transfer requires the explicit watch request including zero',function(){var c=clock(),out=[],errors=[],t=createTransfer(Object.assign(c,{send:function(m){out.push(m);}}));t.start(bytes,release,function(e){errors.push(e);});assert.strictEqual(out.length,0);assert.match(errors[0].message,/request/);t.start(bytes,release,function(){},0);assert.strictEqual(out[0].REQUEST,0);t.cancel();});
function updaterHarness(){
  var c=clock(),out=[],requests=[],u=createUpdater(Object.assign(c,{config:config,send:function(m){out.push(m);},fetch:function(url,max,binary,timeout,cb){var pending={url:url,binary:binary,callback:cb,aborted:0};requests.push(pending);return function(){pending.aborted+=1;cb(new Error('Aborted synchronously'));};}}));
  u.state({version:1,pending:0,flags:1,request:7});
  return{u:u,out:out,requests:requests,clock:c};
}
function completeTransfer(h,status){
  while(h.u.busy()){
    var m=h.out[h.out.length-1];if(m.TYPE!==5&&m.TYPE!==6&&m.TYPE!==7)break;
    h.u.receive({TYPE:8,SESSION:m.SESSION,SEQ:m.TYPE===7?65535:m.SEQ||0,STATUS:m.TYPE===7?status:0,FLAGS:m.TYPE});
  }
}
test('Restore during manifest or payload download aborts once and suppresses obsolete callbacks',function(){
  ['manifest','payload'].forEach(function(stage){
    var h=updaterHarness();h.u.check(7,true);
    if(stage==='payload')h.requests[0].callback(null,JSON.stringify(feed));
    var obsolete=h.requests[h.requests.length-1];h.u.cancel();
    assert.strictEqual(obsolete.aborted,1);assert.strictEqual(h.u.busy(),false);
    assert.strictEqual(h.out[h.out.length-1].STATUS,5);assert.strictEqual(h.out[h.out.length-1].REQUEST,7);
    h.u.state({version:1,pending:0,flags:1,request:8});h.u.check(8,true);
    var newRequest=h.requests[h.requests.length-1],sent=h.out.length,fetches=h.requests.length;
    obsolete.callback(null,stage==='manifest'?JSON.stringify(feed):bytes);obsolete.callback(new Error('Late abort'));
    assert.strictEqual(h.out.length,sent);assert.strictEqual(h.requests.length,fetches);assert.strictEqual(h.u.busy(),true);
    h.u.cancel();assert.strictEqual(newRequest.aborted,1,'old callback must not clear the new cancellation handle');
    assert.strictEqual(h.out.some(function(m){return m.TYPE===5;}),false);
  });
});
test('Restore during transfer rejects old ACKs after a new check and binds BEGIN to its request',function(){
  var h=updaterHarness();h.u.check(7,true);h.requests[0].callback(null,JSON.stringify(feed));h.requests[1].callback(null,bytes);
  var obsolete=h.out[h.out.length-1];assert.strictEqual(obsolete.TYPE,5);assert.strictEqual(obsolete.REQUEST,7);
  h.u.cancel();h.u.state({version:1,pending:0,flags:1,request:8});h.u.check(8,true);
  h.requests[2].callback(null,JSON.stringify(feed));h.requests[3].callback(null,bytes);
  var current=h.out[h.out.length-1],sent=h.out.length;assert.strictEqual(current.REQUEST,8);assert.notStrictEqual(current.SESSION,obsolete.SESSION);
  h.u.receive({TYPE:8,SESSION:obsolete.SESSION,SEQ:0,STATUS:0,FLAGS:5});assert.strictEqual(h.out.length,sent);
  completeTransfer(h,3);assert.strictEqual(h.u.busy(),false);assert.strictEqual(h.out[h.out.length-1].REQUEST,8);assert.strictEqual(h.out[h.out.length-1].STATUS,3);
});
test('Restore between future and current downloads prevents the remaining current transfer',function(){
  var h=updaterHarness(),futureBytes=fixture(3,'2026-10-03'),future=fixture.release(futureBytes,'https://feed.example/releases/3.bin'),two=clone(feed);two.upcoming=future;
  h.u.check(7,true);h.requests[0].callback(null,JSON.stringify(two));assert.strictEqual(h.requests[1].url,future.url);
  h.requests[1].callback(null,futureBytes);completeTransfer(h,4);
  assert.strictEqual(h.requests[2].url,release.url);var currentDownload=h.requests[2],begins=h.out.filter(function(m){return m.TYPE===5;}).length;
  h.u.cancel();assert.strictEqual(currentDownload.aborted,1);currentDownload.callback(null,bytes);
  assert.strictEqual(h.out.filter(function(m){return m.TYPE===5;}).length,begins);assert.strictEqual(h.u.busy(),false);
  h.clock.advance(30000);assert.strictEqual(h.out.filter(function(m){return m.TYPE===5;}).length,begins);
});
test('synchronous fetch completion cannot retain an obsolete abort handle',function(){
  var c=clock(),out=[],aborts=0,u=createUpdater(Object.assign(c,{config:config,send:function(m){out.push(m);},fetch:function(url,max,isBinary,timeout,cb){cb(null,JSON.stringify(feed));return function(){aborts+=1;};}}));
  u.state({version:2,pending:0,flags:1});u.check(0,true);assert.strictEqual(u.busy(),false);u.cancel();assert.strictEqual(aborts,0);assert.strictEqual(out[out.length-1].STATUS,2);
});
console.log(count+' phone unit scenarios passed');
